# Generated by Django 5.0 on 2023-12-15 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('class_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=4)),
                ('user_type', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('destination', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=25)),
                ('student_address', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=25)),
                ('student_address', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('class_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('h1', models.BooleanField(default=1)),
                ('h2', models.BooleanField(default=1)),
                ('h3', models.BooleanField(default=1)),
                ('h4', models.BooleanField(default=1)),
                ('h5', models.BooleanField(default=1)),
                ('h6', models.BooleanField(default=1)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=15)),
                ('h1', models.BooleanField(default=1)),
                ('h2', models.BooleanField(default=1)),
                ('h3', models.BooleanField(default=1)),
                ('h4', models.BooleanField(default=1)),
                ('h5', models.BooleanField(default=1)),
                ('h6', models.BooleanField(default=1)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.classroom')),
            ],
        ),
    ]
