# Generated by Django 5.0 on 2023-12-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='destination',
            field=models.BooleanField(default=3),
        ),
    ]
