# Generated by Django 5.0 on 2023-12-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0005_student_user_id_teacher_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='profileimages'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='profileimages'),
        ),
    ]
