# Generated by Django 5.0 on 2023-12-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0009_teacher_teacher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
