# Generated by Django 5.0 on 2023-12-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0010_alter_student_image_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='h1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='h2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='h3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='h4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='h5',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='h6',
            field=models.CharField(max_length=30),
        ),
    ]
